<!-- AFFICHE LES ERREURS DE CONNEXION SI PRESENTES -->
        <p class="text-center text-danger"><?php if (isset($error)) {echo $error;}?></p>
<form id="login-form" class="loginForm text-center" action="<?=$requestUrl?>/user/login" method="post">
<section class="row text-center">
  <h2 style="margin:0 auto">Connexion</h2>  
  <div class="col-md-12 login-inputs">
  <div class="input my-4">
          <label for="Email">Email</label>
          <input type="text" name="email"  id="Email" class="form-control" placeholder="Email" required="required">
  </div>    
  <div class="input m-5">
      <label for="Pass">Mot de passe</label>
      <input type="password" name="pass"
      id="Pass" class="form-control" placeholder="Password" required="required">
    </div>
  </div>
</section>
<button class="btn btn-primary text-center my-5" type="submit">Connexion</button>
</form>
