<h1 class="text-center my-5">Connexion</h1>
<!-- AFFICHE LES ERREURS DE CONNEXION SI PRESENTES -->
        <p class="text-center text-danger"><?php if (isset($error)) {echo $error;}?></p>
<form id="login-form" class="loginForm text-center" action="<?=$requestUrl?>/user/login" method="post">
<div class="row">  
  <div class="col-md-12 login-inputs">
  <div class="input my-4">
          <input type="text" name="email" value="" id="Email" class="form-control" placeholder="Email" required="required">
  </div>    
  <div class="input">
          <input type="password" name="pass" value="" id="Pass" class="form-control" placeholder="mot de passe" required="required">
  </div>
  </div>
</div>
<button class="btn btn-primary text-center my-5" type="submit">Connexion</button>
</form>
