<!DOCTYPE HTML>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Ce site a pour objectif de vous présenter mon travail artistique qui s’articule autour du dessin et de la peinture. Aquarelle, Huile, Dessins, Paysages, Fleur, Portrait, Architecture" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Patricia Masuy Art</title>
    <link rel="apple-touch-icon" sizes="57x57" href="<?=$wwwUrl?>\images\icons\apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<?=$wwwUrl?>\images\icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?=$wwwUrl?>\images\icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?=$wwwUrl?>\images\icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?=$wwwUrl?>\images\icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?=$wwwUrl?>\images\icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<?=$wwwUrl?>\images\icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?=$wwwUrl?>\images\icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?=$wwwUrl?>\images\icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?=$wwwUrl?>\images\icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=$wwwUrl?>\images\icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?=$wwwUrl?>\images\icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=$wwwUrl?>\images\icons/favicon-16x16.png">
    <link rel="manifest" href="<?=$wwwUrl?>\images\icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<?=$wwwUrl?>\images\icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="<?=$wwwUrl?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?=$wwwUrl?>/css/font-awesome-4.3.0.min.css">
    <!-- font -->
    <link href="https://fonts.googleapis.com/css?family=Marck+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Brush+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Da+2&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <link rel="stylesheet" href="<?=$wwwUrl?>/css/all.min.css">
    <link rel="stylesheet" href="<?=$wwwUrl?>/css/style.css">
    <link rel="stylesheet" href="<?=$wwwUrl?>/css/footer.css">
    <link rel="stylesheet" href="<?=$wwwUrl?>/css/animate.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/r-2.2.3/datatables.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



</head>
<body style="background-color: #2c2f33">

<!-- Barre de navigation -->
<nav class="user-interface" id="user-interface">
    <a href="<?=$requestUrl?>#header">
            <h1 class="title">Patricia Masuy Art</h1>
        </a>
    <ul class="link-list" >
        <!-- Liens vers les differente pages du site -->

        <li><a href="<?=$requestUrl?>#header" rel="home"><i class="fas fa-home"></i>&nbsp; Accueil</a></li>
        <li><a href="<?=$requestUrl?>#latestCreations" rel="about"><i class="fa fa-user"></i>&nbsp; Biographie</a></li>
        <li><a href="<?=$requestUrl?>/gallery" rel="gallery"><i class="fas fa-images"></i>&nbsp; Galerie</a></li>

            <?php if ($userSession->isAdmin()): ?>
                <!-- bouton de deconnexion -->
                <li><a href="<?=$requestUrl?>/user/logout" rel="logout"><i class="fa fa-sign-out-alt"></i>&nbsp; Deconnexion</a></li>
            <?php endif?>
    </ul>
</nav>
<!-- Navigation pour mobile -->
<nav class="mobile-nav" id="mobile-nav">
            <input type="checkbox" id="nav-toggle" class="mobile-nav__checkbox">
            <label for="nav-toggle" class="mobile-nav__btn"><i class="fas fa-bars mobile-nav__icon"></i></label>
            <div class="mobile-nav__background">&nbsp;</div>
            <div class="mobile-nav__navigation">
                <ul class="mobile-nav__list">
                    <li class="mobile-nav__item"><a href="<?=$requestUrl?>" class="mobile-nav__link">Accueil</a></li>
                    <li class="mobile-nav__item"><a href="<?=$requestUrl?>/gallery" class="mobile-nav__link">Galerie</a></li>
                    <li class="mobile-nav__item"><a href="<?=$requestUrl?>/#about" class="mobile-nav__link">Biographie</a></li>
                    <?php if ($userSession->isAdmin()): ?>
                    <li class="mobile-nav__item"><a href="<?=$requestUrl?>/user/logout" class="mobile-nav__link">Deconnexion</a></li>
                    <?php endif?>
                </ul>
            </div>
    </nav>


<!-- En-tête commune -->

<header class="header" id="header" style="background-image: linear-gradient(to top right,#ff0000a2, #fffb009c )  ,url('<?=$wwwUrl?>/images/bg2.jpg');">
    <div id="profile" class="header__profile text-center">
        <div class="profile">
            <div class="profile-pict">&nbsp;</div>
        </div>
        <h4>patricia masuy</h4>
        <p>Artiste Independante</p>
        <ul class="socialMedia-icons header-social-media">
            <li><a href="https://www.facebook.com/patricia.masuy.73" target="_blank" rel="noopener"><i class="fab fa-facebook-square social-icon"></i></a></li>
            <li><a href="https://www.instagram.com/patricia_masuy_art/" target="_blank" rel="noopener"><i class="fab fa-instagram social-icon"></i></a></li>
            <li><a href="#" rel="noopener"><i class="fab fa-pinterest-square social-icon"></i></a></li>
        </ul>
    </div>
</header>




<?php if ($userSession->isAdmin() && strpos($_SERVER['REQUEST_URI'], "admin") == false): ?>

    <!-- Bouton d'acces au panel admin -->
    <a href="<?=$requestUrl?>/admin" style="z-index: 1000;  width: 80px; height: 80px; right:1.5rem; bottom: 1.5rem;" rel="adminButton"><i class="fas fa-th admin-icon" style="z-index: 1000; position:fixed; font-size: 40px; right:1.5rem; bottom:1.5rem;  "></i></a>
<?php endif?>


<main class="animated fadeIn" style="height:100%;">

    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template']?>
</main>




<!-- Pied de page commun -->
<footer>
    <div class="footer">
        <ul>
            <li><h3 class="footer-title">Contactez moi:</h3></li>
            <li>Patricia Masuy</li>
            <li><a href="mailto:patou.masuy@gmail.com"><i class="fas fa-envelope"></i>&nbsp; patou.masuy@gmail.com</a></li>

        </ul>
        <div class="socialMedia">
            <h3 class="footer-title">Suivez moi sur:</h3>
            <ul class="socialMedia-icons">
                <li><a href="https://www.facebook.com/patricia.masuy.73" target="_blank" rel="noopener"><i class="fab fa-facebook-square"></i></a></li>
                <li><a href="https://www.instagram.com/patricia_masuy_art/" target="_blank" rel="noopener"><i class="fab fa-instagram"></i></a></li>
                <li><a href="#" rel="noopener"><i class="fab fa-pinterest-square"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="mentions">
        <small>patricia's artStudio &copy; Copyright 2020. Tous droits réservés.</small>
    </div>
</footer>
<?php if ($userSession->isAdmin()): ?>
<!-- ADMIN-MODAL -->
<div class="modal fade" tabindex="-1" id="mymodal" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content text-black">
                            <div class="modal-header">
                                <h3>Effacer</h3>
                            </div>
                            <div class="modal-body">
                                <p>Etes vous sur de vouloir effacer cette peinture?</p>

                                <div class="row">
                                    <div class="col-md-6">
                                        <img id="moddal-photo" style="width:50%" alt="painting">
                                    </div>
                                    <div class="col-md-6">
                                        <input class="hidden-input" type="text" id="paintName" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a href="<?=$requestUrl?>/remove?id=" id="removePaintBtn" class="btn btn-primary">oui</a>
                                <button class="btn btn-danger" data-dismiss="modal">annuler</button>
                            </div>
                        </div>
                    </div>
                </div>
<?php endif ?>


<!-- Code principal JavaScript de l'application -->

<script src="<?=$wwwUrl?>/js/utilities.js"></script>
<script src="<?=$wwwUrl?>/js/bootstrap.min.js"></script>
<script src="<?=$wwwUrl?>/js/dialog.js"></script>
<script src="<?=$wwwUrl?>/js/nav.js"></script>

</body>
</html>