<h2 class="heading-primary my-4 p-4">Nouvelle peinture</h2>
<section class="row newpaintingForm" >
<form action="<?=$requestUrl?>/upload" method="POST" class="d-flex justify-content-around w-100" enctype="multipart/form-data">
    <div class="col-md-4 col-sm-12">
        <div class="input">
        <label for="name" >Name</label>
        <input type="text" name="name" id="name" class="form-control" placeholder="nom de l'image" required="required">
        </div>
        <div class="form-group">
            <label for="Description">Description</label>
            <textarea style="font-size:1.6rem;" class="form-control" name="desc" id="Description" rows="3" placeholder="Une description courte de la peiture" required="required"></textarea>
        </div>
        
        <div class="form-group">
        <label for="category">Category:</label>
        <select class="form-control" name="category" id="category">
        <option value="">Chosissez...</option>
        <?php foreach ($categories as $key => $category): ?>
        <option value="<?=$category["Id"]?>"><?=$category["Category_Name"]?></option>
        <?php endforeach?>
        </select>
    </div>
    <div class="form-group">
        <label for="theme">Theme:</label>
        <select class="form-control" name="theme" id="theme">
        <option value="">Chosissez...</option>
        <?php foreach ($themes as $key => $theme): ?>
        <option value="<?=$theme["Id"]?>"><?=$theme["Theme_Name"]?></option>
        <?php endforeach?>
        </select>
    </div>
    </div>
    <div class="col-md-4 col-sm-12">
    <div class="input">
        <label for="hauteur">Hauteur (cm)</label>
        <input type="number" name="height" id="hauteur" class="form-control" placeholder="hauteur (cm)" required="required">
        </div>
        <div class="input">
        <label for="Largeur">Largeur (cm)</label>
        <input type="number" name="width" id="Largeur" class="form-control" placeholder="Largeur (cm)" required="required">
    </div>
    <div class="form-check my-3">
                <input class="form-check-input" type="radio" name="availability" id="disponible" value="1" required="required">
                <label class="form-check-label" for="disponible">
                  &nbsp;Disponible
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="availability" id="non-disponible" value="0" required="required">
                <label class="form-check-label" for="non-disponible">
                  &nbsp;Non-Disponible
                </label>
              </div>
    <div class="form-group my-4">
    <label for="fileToUpload">Peinture</label>
    <input type="file" class="form-control-file" name="fileToUpload" id="fileToUpload">
    <div class="uploadForm" id="uploadForm"></div>
  </div>
  <div class="col-md-2 text-center">
      <button class="btn btn-success" type="submit">Upload</button>
  </div>
  </form>
</section>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="<?= $wwwUrl ?>\js\fileScript.js"></script>