<h2 class="gallery-heading heading-primary">Galerie</h2>
<section class="gallery">
    <div class="gallery__techniques" id="btns">

    <!-- BOUTONS AFFICHER TOUTE LES PEINTURES, DEFAULT AU CHARGEMENT DE LA PAGE -->
    <a data-category="0" class="gallery__techniques-item">toutes</a>

        <div class="cat">
        <!-- BOUTONS AFFICHER PAR CATEGORIES -->
        <?php foreach ($categories as $key => $category): ?>
            <a class="gallery__techniques-item" data-category="<?=$category["Id"]?>" data-name="category"><?=$category["Category_Name"]?></a>
        <?php endforeach?>
        </div>
        
        <div class="cat" >
        <!-- BOUTONS AFFICHER PAR THEMES -->
        <?php foreach ($themes as $key => $theme): ?>
            <a class="gallery__techniques-item" data-theme="<?=$theme["Id"]?>" data-name="theme"><?=$theme["Theme_Name"]?></a>
        <?php endforeach?>
        </div>
    </div>

    <!-- CONTAINNER DES PEINTURES, REMPLI DYNAMIQUEMENT EN AJAX  -->
    <div class="gallery__pictures" id="byCategory"></div>

</section>
<script src="<?=$wwwUrl?>/js/utilities.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="<?=$wwwUrl?>/js/gallery.js"></script>


