<a href="javascript:history.go(-1)"  class="back-btn"><i class="fas fa-arrow-left"></i></a>
    
    <section class="showImage row">
    
        <article class="col-md-8 col-sm-12 u-center-text" id="<?=$paint["Name"]?>">
            <img src="<?=$wwwUrl?>/images/paints/<?=$paint["Photo"]?>" class="animated fadeInLeft img-fluid paint-view my-5" style="max-height:50vh; width: auto;"  alt="peinture selectioner">
        </article>

        <aside class="paintDetail col-md-4 col-sm-12 my-5">
            <h2 class="heading-primary"><?=$paint["Name"]?></h2>
            <h3><em><q><?=$paint["Description"]?></q></em></h3>
            <p>Format&nbsp;:&nbsp;<?=$paint["Width"]?>x<?=$paint["Height"]?> cm</p>
            <p>Technique&nbsp;:&nbsp;<?=$paint["Category_Name"]?></p>
            <p>Collection&nbsp;:&nbsp;<?=$paint["Theme_Name"]?></p>
            <?php if($paint["Availability"] == true):?>
                <p class="availability"><em>Disponible</em></p>
            <?php else:?>
                <p class="availability"><em>Non Disponible</em></p>
            <?php endif?>
            <div class="social-media-links">
                <h3><i class="fas fa-heart animated infinite heartBeat share"></i>&nbsp; Soutenez mon travail en partageant&nbsp;!</h3>
                <a href="http://www.facebook.com/sharer.php?u=<?=$wwwUrl?>/showpaint?id=<?=$paint["Id"]?>" target="_blank" rel="noopener">
                    <img src="https://simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" />
                </a>&nbsp;
                <a href="http://pinterest.com/pin/create/button/?url=<?=$wwwUrl?>/showpaint?id=<?=$paint["Id"]?>&description=<?=$paint["Name"]?>" rel="noopener">
                    <img src="https://simplesharebuttons.com/images/somacro/pinterest.png" alt="Pinterest" />
                </a>&nbsp;
                <a href="mailto:?&amp;Body=<?=$wwwUrl?>/showpaint?id=<?=$paint["Id"]?>" rel="noopener">
                    <img src="https://simplesharebuttons.com/images/somacro/email.png" alt="Email" />
                </a>
            </div>
        </aside>
    </section>
