<!-- Table styles -->
<style>
DIV.table 
{
    display:table;
    padding: 20px;
}
FORM.tr, DIV.tr
{
    display:table-row;
    height: 45px;
}

SPAN.td
{
    display:table-cell;
}
SPAN.td:nth-child(-n+3) {
  padding-right:20px;
}
</style>

<!-- flashbag message -->
<?php if ($message): ?>

<h3 class="text-center flashbag"><?=$message?></h3>

<?php endif?>

<!-- admin pannel -->
<section class="admin-panel">
<h2 class="heading-primary mx-5">Panel Admin</h2>
    <div class="admin-header  my-5">
            <h3>Modification</h3>
            <a type="button"  href="<?=$requestUrl?>/admin/addPaint" id="addPaintBtn" class="btn btn-success "><i class="fas fa-plus"></i>&nbsp;Ajouter une peinture</a>
        </div>
    <div class="row">

        <!-- TABLEAU DES CATEGORIES -->
        <div class="col-md-6">
        <div class="table table-dark table-hover">
            <div class="tr">
                <span class="td">#</span>
                <span class="td">Technique</span>
                <span class="td">Modifier</span>
                <span class="td">Supprimer</span>
            </div>
            <?php foreach ($categories as $key => $categorie): ?>
            <form class="tr" method="post" action="<?=$requestUrl?>/adminedits">
                <span class="td"><?=$key+1?><input type="number" name="id" value="<?=$categorie['Id']?>" hidden></span>
                <span class="td">
                <input type="text" name="category" value="<?=$categorie['Category_Name']?>" class="form-control edit-input" placeholder="FirstName">
                </span>
                <span class="td"><input class="btn btn-primary" style="padding:5px 15px;" type="submit" name="editCategory" value="Modifier"></span>
                <span class="td"><input class="btn btn-danger" style="padding:5px 15px;" type="submit" name="removeCategory" value="Effacer"></span>
            </form>
            <?php endforeach?>
            <form class="tr" action="<?=$requestUrl?>/adminedits" method="POST">
                <span class="td"><?= count($categories)+1 ?></span>
                <span class="td">
                <input type="text" name="newCategory" class="form-control edit-input" placeholder="Ajouter une technique" required>
                </span>
                <button type="submit" class="btn btn-success">Ajouter</button>
            </form>
        </div>
        </div>
        <div class="col-md-6">
        <!-- TABLEAU DES THEMES -->
        <div class="table table-dark table-hover">
            <div class="tr">
                <span class="td">#</span>
                <span class="td">Technique</span>
                <span class="td">Modifier</span>
                <span class="td">Supprimer</span>
            </div>
            <?php foreach ($themes as $key => $theme): ?>
            <form class="tr" method="post" action="<?=$requestUrl?>/adminedits">
                <span class="td"><?=$key+1?><input type="number" name="id" value="<?=$theme['Id']?>" hidden></span>
                <span class="td">
                <input type="text" name="theme" value="<?=$theme['Theme_Name']?>" class="form-control edit-input">
                </span>
                <span class="td"><input class="btn btn-primary" type="submit" name="editTheme" value="Modifier" style="width: 50%"></span>
                <span class="td"><input class="btn btn-danger" type="submit" name="removeTheme" value="Effacer" style="width: 50%"></span>
            </form>
            <?php endforeach?>
            <form class="tr" action="<?=$requestUrl?>/adminedits" method="POST">
                <span class="td"><?= count($themes)+1 ?></span>
                <span class="td">
                <input type="text" name="newTheme" class="form-control edit-input" placeholder="Ajouter un theme" required>
                </span>
                <button type="submit" class="btn btn-success">Ajouter</button>
            </form>
        </div>           
        </div>
    </div>

    <!-- TABLEAU DES PEINTURE -->
    <div class="display responsive ">
        <table class="table table-dark table-hover" style="width:100%" id="datatable">
        <thead>
            <tr>
            <th scope="col" >#</th>
            <th scope="col">Nom</th>
            <th scope="col">Description</th>
            <th scope="col" data-priority="1">Photo</th>
            <th scope="col">Format</th>
            <th scope="col">Technique</th>
            <th scope="col">Theme</th>
            <th scope="col" data-priority="2">Modifier</th>
            <th scope="col" data-priority="3">Effacer</th>
            </tr>
        </thead>
        <tbody>
                <?php foreach ($paints as $key => $paint): ?>
                <tr>
                    <td><?=$paint['Id']?></td>
                    <td><?=$paint['Name']?></td>
                    <td><?=$paint['Description']?></td>
                    <?php if($paint['Photo']): ?>
                    <td><img src="<?=$wwwUrl?>/images/paints/<?=$paint['Photo']?>" class="admin-table-image" alt="peinture"></td>
                    <?php else: ?>
                        <td>pas d'image</td>
                    <?php endif?>
                    <td><?=$paint['Width']?>x<?=$paint['Height']?> cm</td>
                    <td><?=$paint['Category_Name']?></td>
                    <td><?=$paint['Theme_Name']?></td>
                    <td><a href="<?=$requestUrl?>/admin/editPaint?id=<?=$paint['Id']?>#<?=$paint["Photo"]?>" class="btn btn-primary">Modifier</a></td>
                    <td><a type="button" data-toggle="modal" data-id="<?=$paint['Id']?>" data-photo="<?=$paint['Photo']?>" data-name="<?=$paint['Name']?>" data-target="#mymodal" class="btn btn-danger open-AddBookDialog">Effacer</a></td>

                </tr>
                <?php endforeach?>
            </tbody>
            <tfoot>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Photo</th>
                <th scope="col">Format</th>
                <th scope="col">Technique</th>
                <th scope="col">Theme</th>
                <th scope="col">Modifier</th>
                <th scope="col">Effacer</th>

                </tr>
            </tfoot>
        </table>
    </div>
</section>




<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="<?=$wwwUrl?>/js/dataTable.js"></script>



