<!-- flashbag message -->
<?php if ($message): ?>

<h3 class="text-center flashbag"><?=$message?></h3>

<?php endif?>

<!-- admin pannel -->
<div class="admin-panel">
<h2 class="heading-primary mx-5">Panel Admin</h2>
    <div class="admin-header  my-5">
            <div></div>
            <a type="button"  href="<?=$requestUrl?>/admin/addPaint" id="addPaintBtn" class="btn btn-success "><i class="fas fa-plus"></i>&nbsp;Ajouter une peinture</a>
        </div>
    <div class="row">

        <!-- TABLEAU DES CATEGORIES -->
        <div class="col-md-6">
        <table class="table table-dark table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Techniques</th>
                    </tr>                    
                </thead>
                <tbody>
                <?php foreach ($categories as $key => $categorie): ?>
                    <tr>
                        <form action="<?=$requestUrl?>/adminedits" method="POST">
                        <td><?=$key+1?><input type="number" name="id" value="<?=$categorie['Id']?>" hidden></td>
                        <td>
                        <div class="input">
                            <input type="text" name="category" value="<?=$categorie['Category_Name']?>" class="form-control edit-input" placeholder="FirstName">
                        </div>
                        </td>
                        <td><input class="btn btn-primary" type="submit" name="editCategory" value="Modifier" style="width: 50%"></td>
                        <td><input class="btn btn-danger" type="submit" name="removeCategory" value="Effacer" style="width: 50%"></td>
                        </form>

                    </tr>
                    <?php endforeach?>
                    <tr>
                        <form action="<?=$requestUrl?>/adminedits" method="POST">
                        <td><?= count($categories)+1 ?></td>
                        <td>
                        <div class="input">
                            <input type="text" name="newCategory" value="" class="form-control edit-input" placeholder="Ajouter une technique" required>
                        </div>
                        </td>
                        <td></td>
                        
                        <td><button type="submit" class="btn btn-success">Ajouter</button></td>
                        </form>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">

        <!-- TABLEAU DES THEMES -->
        <table class="table table-dark table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Themes</th>
                    </tr>                    
                </thead>
                <tbody>
                    <?php foreach ($themes as $key => $theme): ?>
                    <tr>
                        <form action="<?=$requestUrl?>/adminedits" method="POST">
                        <td><?=$key+1?><input type="number" name="id" value="<?=$theme['Id']?>" hidden></td>
                        <td>
                        <div class="input">
                            <input type="text" name="theme" value="<?=$theme['Theme_Name']?>" class="form-control edit-input" placeholder="FirstName">
                        </div>
                        </td>
                        <td><input class="btn btn-primary" type="submit" name="editTheme" value="Modifier" style="width: 50%"></td>
                        <td><input class="btn btn-danger" type="submit" name="removeTheme" value="Effacer" style="width: 50%"></td>
                        </form>

                    </tr>
                    <?php endforeach?>
                    <tr>
                        <form action="<?=$requestUrl?>/adminedits" method="POST">
                        <td><?= count($themes)+1 ?></td>
                        <td>
                        <div class="input">
                            <input type="text" name="newTheme" value="" class="form-control edit-input" placeholder="Ajouter un theme" required>
                        </div>
                        </td>
                        <td></td>
                        
                        <td><button type="submit" class="btn btn-success">Ajouter</button></td>
                        </form>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <!-- TABLEAU DES PEINTURE -->
    <div class="display responsive ">
        <table class="table table-dark table-hover" style="width:100%" id="datatable">
        <thead>
            <tr>
            <th scope="col" >#</th>
            <th scope="col">Nom</th>
            <th scope="col">Description</th>
            <th scope="col" data-priority="1">Photo</th>
            <th scope="col">Format</th>
            <th scope="col">Technique</th>
            <th scope="col">Theme</th>
            <th scope="col" data-priority="2">Modifier</th>
            <th scope="col" data-priority="3">Effacer</th>
            </tr>
        </thead>
        <tbody>
                <?php foreach ($paints as $key => $paint): ?>
                <tr>
                    <td><?=$paint['Id']?></td>
                    <td><?=$paint['Name']?></td>
                    <td><?=$paint['Description']?></td>
                    <?php if ($paint['Photo']): ?>
                    <td><img src="<?=$wwwUrl?>/images/paints/<?=$paint['Photo']?>" class="admin-table-image" alt="peinture"></td>
                    <?php else: ?>
                        <td><form action=""><input type="file"><button class="btn btn-primary"type="submit">Ajouter</button></form></td>
                    <?php endif?>
                    <td><?=$paint['Width']?>x<?=$paint['Height']?> cm</td>
                    <td><?=$paint['Category_Name']?></td>
                    <td><?=$paint['Theme_Name']?></td>
                    <td><a href="<?=$requestUrl?>/admin/editPaint?id=<?=$paint['Id']?>#<?=$paint["Photo"]?>" class="btn btn-primary">Modifier</a></td>
                    <td><a type="button" data-toggle="modal" data-id="<?=$paint['Id']?>" data-photo="<?=$paint['Photo']?>" data-name="<?=$paint['Name']?>" data-target="#mymodal" class="btn btn-danger open-AddBookDialog">Effacer</a></td>

                </tr>
                <?php endforeach?>
            </tbody>
            <tfoot>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Photo</th>
                <th scope="col">Format</th>
                <th scope="col">Technique</th>
                <th scope="col">Theme</th>
                <th scope="col">Modifier</th>
                <th scope="col">Effacer</th>

                </tr>
            </tfoot>
        </table>
    </div>
</div>




<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="<?=$wwwUrl?>/js/dataTable.js"></script>



